Feat/#14 add firebase
Recursion-Group-X/bomber-man pull request #21
Opened 2022-12-25 15:39 UTC by pimon0807

### 関連しているIssue / 目的
#14 

### 達成条件
・game終了時に今回の記録をfirebase上に保存
・firebase上に保存してある記録を取得

### 実装の概要 / このPRの対応範囲
・dataaccessフォルダに保存する記録の型を書いたファイルとfirebaseと接続して、記録を取得、保存するclassを書いたファイルを追加しました。
・Game終了時に現在の記録を保存する関数を追加しました。useIntervalを停止する必要があったので"isAlive"というstateを追加しました。
・Result画面遷移時にfirebase上からデータを取得する関数を追加しました。

### 重点的にレビューして欲しいところ
データの保存、取得はできていると思います。idを連番ではなくfirebase上の自動生成された値を当てています。
firebaseをほぼ使ったことが無いので、もっと良い取得方法やパターンがあれば修正したいです！

### 不安に思っていること
await/catch文でのエラーハンドリングの必要があると思います。(現在は全て仮のalartにしてあります。)
チームでのfirebaseを使ったことが無いのですが、firebase上でメンバーを追加することでデータベースの共有運用できる感じですかね？

### その他情報（スクリーンショット等）
npmでfirebaseを利用できるパッケージをインストールしました。npm iをお願いします。
Home画面時のデータ取得はResullt画面と同じになると思うので、Home画面の修正時に追加するつもりです。

2022-12-25 20:27 UTC, takeshi8989 requested changes

2022-12-25 20:27 UTC, takeshi8989 commented on src/pages/Result.tsx
> +            <div key={record.alivedTime}>
ここのkeyをrecordのidがあればidにしてほしいです！

2022-12-25 20:27 UTC, takeshi8989 commented on src/pages/Result.tsx
> +      return setrecordList(await gameRecordGateway.getGameRecord())
ここではランキング上位のrecordのみが必要だと思うので、新しい関数で必要な分(大体上から5個くらい)だけfetchしてくるやつを使ったほうが良いかもしれません！

2022-12-25 20:27 UTC, takeshi8989 commented on src/dataaccess/gameRecordGateway.ts
> +    postGameRecord(record: GameRecord): void{
ここで出来たらランキング順にソートするといいと思います！orderBy使えばできると思うので

2022-12-25 20:29 UTC, takeshi8989 commented
>firebase上でメンバーを追加することでデータベースの共有運用できる感じですかね？

firebaseコンソールのリンクを共有するか招待？する方法があったはずです！

2022-12-26 13:09 UTC, pimon0807 commented on src/pages/Result.tsx
> +            <div key={record.alivedTime}>
recordにidフィールドを追加しました。このidはデータを登録時にfiresbase上に登録してあるデータ数+1になっています。

2022-12-26 13:09 UTC, pimon0807 commented on src/pages/Result.tsx
> +      return setrecordList(await gameRecordGateway.getGameRecord())
上位5件のrecordを取得する関数を実装しました。

2022-12-26 13:14 UTC, pimon0807 commented
レビューを受けてコードを修正しました。
修正点は、
・recordの上位5つを取得する機能の実装
・recordにidフィールドの追加
です。

firebaseに招待する際にメールアドレスが必要になるそうです。
apikeyの公開と合わせて相談したいです！

2022-12-26 21:45 UTC, takeshi8989 approved these changes
変更確認しました！OKだと思います！

2022-12-29 02:21 UTC, merged